### PR TITLE
Make server more robust.

### LINKED ISSUE #1: Make it a multi-threaded server

### LINKED ISSUE #2: Handle issues when connecting to the gateway

### PR DESCRIPTION
**Pull request by mrstegeman**
* Define a proper message structure, instead of relying on magic
  characters as separators.
* Make server threaded.
* Send proper response messages.

Fixes #1
Fixes #2

### CODE REVIEW

**Review by hobinjk — COMMENTED** [review]
Looks reasonable to me. Unfortunately, since this isn't backwards-compatible we would need to wait until the corresponding change is deployed through an OTA update (at least that's the safest/easiest way to go about it)

**Comment by mrstegeman** [comment]
@hobinjk It should be safe to merge this, as the intent-parser is in the base image. I've added code to update it when doing an OTA update in mozilla-iot/gateway#1317

**Comment by hobinjk** [comment]
The intent parser is already upgraded in post-upgrade.sh with a blind `git pull` (hidden pretty well as the one-line https://github.com/mozilla-iot/gateway/blob/master/tools/post-upgrade.sh#L46). For example, if this is merged today then a 0.5.1 OTA would pull this PR's code from master but still have the base 0.5.1 gateway.

**Comment by mrstegeman** [comment]
Ahh... I see your point. I could add backwards compatibility here for the time being, maybe that's the best way to go.

**Comment by mrstegeman** [comment]
(I didn't realize the intent-parser was already being upgraded.)

**Comment by mrstegeman** [comment]
@hobinjk Backwards-compat is now available.

**Review by hobinjk — APPROVED** [review]
Great! LGTM

**Comment by hobinjk** [comment]
Although merging this should still be delayed to Monday of next week just for paranoia's sake

**Comment by mrstegeman** [comment]
... too late. I can revert.

**Comment by hobinjk** [comment]
Sorry for not realizing earlier that it could cause issues! There are just some interactions between this and the OTA upgrade that are currently untested.

**Comment by mrstegeman** [comment]
No problem. I'll just wait until early next week to merge.

**Pull request merged**
