### PR TITLE
Set the REUSE_ADDR socket option.

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by hobinjk** [comment]
Under what conditions is this necessary? Does Travis try to spin up multiple intent parsers?

**Comment by dhylands** [comment]
I improved run-tests.sh in https://github.com/mozilla-iot/gateway/pull/796 so that you can run `npm test` locally.

When you close an open socket, it doesn't actually shutdown for a couple minutes, even though the process which created the socket has exited. This can be seen by doing a `netstat | grep 5555` immediately after running a successful test run `npm test src/test/integration/commands-test.js` you'll see something like:
```
tcp        0      0 localhost:5555          localhost:42328         TIME_WAIT  
tcp        0      0 localhost:5555          localhost:42326         TIME_WAIT  
tcp        0      0 localhost:5555          localhost:42338         TIME_WAIT  
tcp        0      0 localhost:5555          localhost:42336         TIME_WAIT  
```
If you try to bind to the socket while its in the TIME_WAIT state, then it will fail unless the REUSE_ADDR socket option has been set.

The socket will typically stay in the TIME_WAIT state for a couple minutes after the process closes it.

**Review by hobinjk — APPROVED** [review]
Tested locally and LGTM, thanks for the context!

**Comment by dhylands** [comment]
And RESUE_ADDR is normally only needed on the server side when binding statically assigned port numbers. BSD also has a REUSE_PORT socket option which you also need to consider if writing code which might run on that OS. So in C/C++ you wind up coding something like this:
https://github.com/mozilla-iot/serial-mcu/blob/07e23da1e81d5820968109c9258c377f8a863a9f/ServerSocketPort.cpp#L40-L53
to create portable code.

**Pull request merged**
